# (name, kind, icon) seeded into every new group.
DEFAULT_CATEGORIES: list[tuple[str, str, str]] = [
    ("Ăn uống", "expense", "🍜"),
    ("Đi chợ", "expense", "🛒"),
    ("Di chuyển", "expense", "🛵"),
    ("Nhà cửa", "expense", "🏠"),
    ("Hóa đơn", "expense", "💡"),
    ("Subscription", "expense", "📺"),
    ("Mua sắm", "expense", "🛍️"),
    ("Sức khỏe", "expense", "💊"),
    ("Giáo dục", "expense", "📚"),
    ("Con cái", "expense", "👶"),
    ("Giải trí", "expense", "🎮"),
    ("Hiếu hỉ", "expense", "🎁"),
    ("Gia đình", "expense", "👨‍👩‍👧"),
    ("Du lịch", "expense", "✈️"),
    ("Bảo hiểm", "expense", "🛡️"),
    ("Khác", "expense", "📦"),
    ("Lương", "income", "💼"),
    ("Thưởng", "income", "🎉"),
    ("Thu nhập phụ", "income", "💰"),
    ("Lãi tiết kiệm", "income", "🏦"),
    ("Thu khác", "income", "➕"),
]
